<html>
	<head>
		<title><?=$this->title?></title>
	</head>
	<body>
		<table  width="600" align="center" style="font-family:arial" cellpadding="0" cellspacing="0">
			<tr>
				<td style="background-color: #fff" colspan="3">
					image				
				</td>
			</tr>
			<tr>
				<td height="150" style="font-size:14px;color:#656565;background-color: #fff;border: 1px solid #d7d7d7;padding-left: 20px;padding-right: 30px;box-shadow:1px 1px 6px #D7D7D7;">
					<br/>
					<span style="font-size:18px; color: #AD0101; font-weight:bold;">Dear <?=$this->name?>,</span>
					<p>
					MyStore would like to welcome you as a new customer to our online computer store.<br/>
					We’re sure that you will find our store both user-friendly and reliable.<br/>
					</p>
                                        <p>
					<i>Your personal account information:</i><br/>
					email (login):<span style=""> <?=$this->email?></span><br/>
                                        password:<span style=""> <?=$this->password?></span><br/><br/>
					
					We’re looking forward to seeing you online,<br/>
					</p>
					<br/>
				</td>
			</tr>
			<tr style="height: 15px;background-color: #282828">

			</tr>
		</table>
	</body>
</html>