<div class="jumbotron biglogo">
    <a href="<?php echo $this->url('home') ?>">
        <div class="smallLogo"></div>
    </a>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('О нас'); ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/wordLogo.jpg"/>
                </div>
                <p>
                    <?php echo $this->translate('Компания ООО "АлМаксСтрой" уже более десяти лет на рынке строительства. На сегодняшний день в нашей компании работает более семидесяти высококвалифицированных специалистов.'); ?>
                </p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/default', array('controller' => 'about', 'action' => 'index')) ?>"><?php echo $this->translate('Наша компания') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Наши услуги') ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/panels.png"/>
                </div>
                <br/>
                <p><?php echo $this->translate('Основные виды деятельности нашей компании:<br/><br/>'); ?>
                    <span class="badge">!</span> <?php echo $this->translate('монтаж сэндвич панелей'); ?><br/>
                    <span class="badge">!</span> <?php echo $this->translate('монтаж металлоконструкций'); ?><br/>
                    <span class="badge">!</span> <?php echo $this->translate('электромонтажные работы'); ?><br/>
                </p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/default', array('controller' => 'projects', 'action' => 'index')) ?>"><?php echo $this->translate('Наши Проекты') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Наши контакты') ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/contactus.jpg"/>
                </div>  <br/>
                <address style="float:left;">
                    <strong>Контактные тел.</strong><br>  
                    <abbr title="Phone">RUS:</abbr>+7(909) 5818067<br/>
                    <abbr title="Phone">BLR:</abbr>+375(29) 5126629<br/>
                    <abbr title="Phone">BLR:</abbr>+375(29) 7119193<br/><br/>

                </address>

                <address style="float:right;">
                    <strong>E-mail:</strong><br>
                    <a href="mailto:#">almaksstroy@inbox.ru</a><br>
                    <a href="mailto:#"> maxmontag@mail.ru</a><br>
                    <a href="mailto:#">almaksstroy@mail.ru</a><br>

                </address>



                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('application/default', array('controller' => 'contact-us', 'action' => 'index')) ?>"><?php echo $this->translate('Ваши условия - наша ответственность') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
