<div class="jumbotron biglogo">
    <a href="<?php echo $this->url('home') ?>">
        <div class="smallLogo"></div>
    </a>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('О нас'); ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/wordLogo.jpg"/>
                </div>
                <p>
                    <?php echo $this->translate('Компания ООО "АлМаксСтрой" уже более десяти лет на рынке строительства. На сегодняшний день в нашей компании работает более семидесяти высококвалифицированных специалистов.'); ?>
                </p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Наши услуги') ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/panels.png"/>
                </div>
                <br/>
                <p><?php echo $this->translate('Основные виды деятельности нашей компании:<br/>'); ?>
                    <span class="badge">!</span> <?php echo $this->translate('монтаж сэндвич панелей'); ?><br/>
                    <span class="badge">!</span> <?php echo $this->translate('монтаж металлоконструкций'); ?><br/>
                    <span class="badge">!</span> <?php echo $this->translate('электромонтажные работы'); ?><br/>
                </p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('projects') ?>" target="_blank"><?php echo $this->translate('Our Projects') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Наши контакты') ?></h3>
            </div>
            <div class="panel-body">
                <div class="panel-body-image">
                    <img class="img-rounded" src="/img/main/contactus.jpg"/>
                </div>  <br/>
                <p>«АлМаксСтрой»<br/>
                    Adress:<br/>
                    214036 г. Смоленск <br/>ул. Смольянинова д.15 офис 405<br/><br>
                    Phones:<br/>
                    +7 909 5818067<br/>
                    +375 29 5126629<br/>
                    +375 29 7119193<br/><br/>
                    Contact E-mails:<br/>
                    <a href="mailto:almaksstroy@inbox.ru">almaksstroy@inbox.ru</a><br/>
                    <a href="mailto:maxmontag@mail.ru">maxmontag@mail.ru<br/>
                </p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('We contact with you') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
